- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: '/var/snap/jenkins/4874/workspace/MAV_ANS_CICD/target/MAV_ANSIBLE.war'
        dest: '/opt/tomcat/webapps'

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
