- name: Deploy to Tomcat
	hosts: web
	become: yes
	tasks:
		- name: Copy war file to tomcat
		copy:
		src: '/var/snap/jenkins/4859/workspace/MAV_ANS_CICD/target/MAV_ANSIBLE.war'
		dest: '/opt/tomcat/webapps'
		- name: Restart Tomcat
		systemd:
		name: Tomcat
		state: restarted
